pipeline {
    agent any

    tools {
        maven 'mvn3'
    }

    environment {
        NEXUS_VERSION = "nexus3"
        NEXUS_PROTOCOL = "http"
        NEXUS_URL = "192.168.100.189:8081"
        NEXUS_REPOSITORY = "department-service-repo"
        NEXUS_CREDENTIALS_ID = "nexus-credentials"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Clean') {
            steps {
                sh "mvn --batch-mode clean"
            }
        }

        stage('Unit And Integration Tests') {
            steps {
                sh 'mvn --batch-mode test'
            }
            def pom = readMavenPom file:'pom.xml'
            env.version = pom.version
        }

        stage('Backend Install') {
            steps {
                sh "mvn --batch-mode install -DskipTests"
            }
        }

        stage('Build Docker Image + Push') {
            dir ('department-service') {
                def app = docker.build "localhost:5050/department-service:${env.version}"
                app.push()
            }
        }

        stage ('Run Docker Image') {
            docker.image("localhost:5000/department-service:${env.version}").run('-p 8082:8082 --name department --link service-registry')
        }

        stage('Nexus Repository') {
            steps {
                script {
                    pom = readMavenPom file : "pom.xml"
                    filesByGlob = findFiles(glob: "target/*.${pom.packaging}");
                    artifactPath = filesByGlob[0].path;
                    artifactExists = fileExists artifactPath;
                    if (artifactExists) {
                        echo "*** File: ${aritfactPath}, group: ${pom.groupId}, packaging: ${com.packaging}, version: ${pom.version}";
                        nexusArtifactUploader(
                            nexusVersion: NEXUS_VERSION,
                            protocol: NEXUS_PROTOCOL,
                            nexusUrl: NEXUS_URL,
                            groupId: pom.groupId,
                            version: pom.version,
                            repository: NEXUS_REPOSITORY,
                            credentialsId: NEXUS_CREDENTIALS_ID,
                            artifacts: [
                                [artifactId: pom.artifactId,
                                classifier: '',
                                file: artifactPath,
                                type: pom.packaging],
                                [artifactId: pom.artifactId,
                                classifier: '',
                                file: "pom.xml",
                                type: "pom"
                                ]
                            ]
                        );
                    } else {
                        error "File ${artifactPath} couldn't be found."
                    }
                }
            }
        }

        stage ('Final') {
            build job: 'cloud-gateway-pipeline', wait: false
        }
    }
}